version: '3'
services:
  db:
    image: mariadb
    container_name: sysman
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sysman
      MYSQL_USER: grau
      MYSQL_PASSWORD: 123456
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
#  spring-back:
#    container_name: sysman-back
#    build:
#      context: .
#    image: mary-back
#    ports:
#        - "8080:8080"
